<?php
$title = 'Forgot Password';
$this->headTitle($title);
?>
<?php echo $this->flashMessenger()->render(); ?>
<div class="panel panel-default">
	<div class="panel-heading">
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
    <div class="panel-body">    
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url(
            'login',
            array(
                'controller' => 'login',
                'action' => 'forgotPassword',
            )
        ));
        $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formRow($form->get('email')->setAttribute('class', 'form-control'));
        echo '<br>';
        echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-warning'));
        echo $this->form()->closeTag();
        ?>
        <br>
        <p>
            <a href="<?php echo $this->url('login',array('action' => 'login')); ?>">Did you remember your password?
            </a>
        </p>
    </div>
</div>