<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('BlogApplication'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('BlogApplication') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">

               			<?php   echo $this->navigation('navigation')
										->menu()
										->setMinDepth(0)
										->setMaxDepth(0)
										->setUlClass('nav navbar-nav');
						?>
                    </ul>
					<ul class="nav navbar-nav navbar-right">
						<?php if ($user = $this->identity()): ?>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
									<?php echo $this->escapeHtml($user->getUsername()); ?>
									<span class="caret"></span>
								</a>
								<ul class="dropdown-menu">
									<li><a href="<?php echo $this->url('admin', array('action' => 'index'));?>">Кабинет</a></li>
						            <li role="separator" class="divider"></li>
									<li><a href="<?php echo $this->url('login', array('action'=>'logout')); ?>">Выход</a></li>
								</ul>
					        </li>
						<?php else: ?>
							<li class="pull"><a href="<?php echo $this->url('register') ?>">Регистрация</a></li>
							<li class="pull"><a href="<?php echo $this->url('login') ?>">Вход</a></li>
						<?php endif ?>
					</ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php
                //echo $this->navigation('navigation')
                  //->breadcrumbs()
                  //->setMinDepth(0)
                  //->setPartial('partial/breadcrumb.phtml');
            ?>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
            </div>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
