<?php
    $title = 'Delete User';
    $this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure you want to delete this user?</p>
<?php 
    $url = $this->url('user', array('action' => 'delete', 'id'=>$user->getId())); 
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $user->getId(); ?>" />
        <input type="submit" name="del" value="Yes" class="btn btn-primary"/>
        <input type="submit" name="del" value="No" class= "btn btn-danger"/>
    </div>
</form>