<?php
    $title = 'Edit My Profile';
    $this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('user',array(
            'action' => 'profileUser',
            'id'     => $this->id,
        )
    ));
    $form->prepare();
    echo $this->form()->openTag($form);
?>
<div id="form-profile-user">
    <?php echo $this->formHidden($form->get('id')); ?>
    <div class="name">
        <?php echo $this->formRow($form->get('name')->setAttribute('class', 'form-control')); ?>
    </div>
    <div class="surname">
        <?php echo $this->formRow($form->get('surname')->setAttribute('class', 'form-control')); ?>
    </div>
<?php
    echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-warning'));
    echo $this->form()->closeTag();
?>
</div>
