<?php
    $title = 'Contact';
    $this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php echo $this->flashMessenger()->render();?>
<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('contact', array('action' => 'contact')));
    $form->prepare();
    echo $this->form()->openTag($form);
?>
<div id="form-contact">
    <div class="name">
        <?php echo $this->formRow($form->get('name')->setAttribute('class', 'form-control')); ?> 
    </div>
    <div class="email">
        <?php echo $this->formRow($form->get('email')->setAttribute('class', 'form-control')); ?> 
    </div>
    <div class="comment">
        <?php echo $this->formRow($form->get('comment')->setAttribute('class', 'form-control')); ?> 
    </div>
    <?php
        echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-success'));
        echo $this->form()->closeTag();
    ?>
</div>